### ISSUE TITLE
Cannot covert Noto Emoji

### ISSUE THREAD

**Issue by huming2207** [littlevgl/utils#27]
Hi there,

I'm trying to covert the Noto Emoji font to bitmap with this tool. Then I've got a problem.

Here's what the char map supposed to be: 

![image](https://user-images.githubusercontent.com/4463497/57578928-1ffdde80-74d8-11e9-992f-bcd9cb24ca31.png)

Here's the conversion result:

![image](https://user-images.githubusercontent.com/4463497/57578947-5b98a880-74d8-11e9-9379-879adb764ba4.png)

My configuration is:

![image](https://user-images.githubusercontent.com/4463497/57578954-79fea400-74d8-11e9-9c58-7bc0250315f2.png)

I've tried ticking the "Convert compatible symbol font". It works, but only a certain range of the symbol are converted.

Here are the font file and the result:

[NotoEmoji-Regular.ttf.zip](https://github.com/littlevgl/lv_utils/files/3169817/NotoEmoji-Regular.ttf.zip)

[noto_emoji_50.c.zip](https://github.com/littlevgl/lv_utils/files/3169816/noto_emoji_50.c.zip)

Regards,
Jackson

**Comment by kisvegabor** [comment]
Hi,

if you load the font in [FontForge](https://fontforge.github.io/en-US/) you can see that the emojis starts at 0x1F200  instead of 32.

However, the font converter can't convert characters above 0xFFFF. I modified the font and moved the Emojis to 0xE000. [NotoEmoji_mod.ttf.zip](https://github.com/littlevgl/lv_utils/files/3171062/NotoEmoji_mod.ttf.zip) 
Check it in FontForge.

I tested it like this:
![image](https://user-images.githubusercontent.com/7599318/57594910-99321b80-7542-11e9-93ef-23891f1d071e.png)

[emoji.c.zip](https://github.com/littlevgl/lv_utils/files/3171068/emoji.c.zip)

**Comment by huming2207** [comment]
Hello @kisvegabor 

Thanks for your reply. Now I get it. Indeed it is the font's issue.

Regards,
Jackson

**Comment by kisvegabor** [comment]
Great!
