### ISSUE TITLE
Font generate binary

### ISSUE THREAD

**Issue by shlsyc** [littlevgl/utils#6]
For Chinese characters, in general, font files are quite large, so the generated C files are quite large. Can provide functions of generating binary files?

**Comment by kisvegabor** [comment]
Unfortunately there is no binary font type explicitly now. However you can do it with a small script which reads to C file and writes it to binary file.
  
I suppose you don't need all the Chinese characters. You can use sparse fonts too (where there a gap because not all letters are included) Use the "List" field of the converter for this purpose. Maybe it helps to avoid dealing with binary files.

**Comment by shlsyc** [comment]
Thank you for your advice
